### ISSUE TITLE
[CR] B12.1 Defer improved handling of product versioning

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-swg#16]
**Added to Release Plan:**
_links to tasks being added to release plan_

**Removed from Release Plan:**
https://github.com/NASA-PDS/registry/issues/55
_links to tasks being removed from release plan_

**Rationale:**
Not critical yet, focused for this release on a robust v1 release of the registry and management of scalable harvesting for bigger bundles.

**Comment by jordanpadams** [comment]
Reviewed with SWG and issue has been completed as part of B13.0
